### ISSUE TITLE
what is the point of this repo + a few issues/improvements

### ISSUE THREAD

**Issue by cqdetdev** [aabstractt/aurial#2]
I thought my eyes were deceiving me when I initially opened this repo but then I did a double take and realized that I wasn't going insane.

First of all, what is the point of this repo exactly? The concept of a handler manager isn't something foreign and quite often useful in some contexts (but even then, Dragonfly's default handler/event system is already extremely simple and concise to use), but I struggle to find exactly what problem this repo serves.

The player/world directory is just essentially just an abstraction of Dragonfly's event system with "registries" which just look to be a way to stack multiple handler logic (a common, valid issue in DF) along with abstractions for each handler with abstracted contexts for each. This entire code is just unneeded and problematic.

First of all, the recent Dragonfly (world tx) updates, handlers are now thread safe and don't require mutex's or atomics (for fields or general usage). The code in this repository requires a call to `(Registry).All()` which has to constantly lock and unlock a registry lock every time an event is called (for all events). This defeats the entire purpose of moving away from needing thread-guarding structures.

Secondly, the context abstraction is literally useless. It is already extremely easy to use Dragonfly handlers as the arguments are passed in directly to each function, adding a context just adds a useless access (e.g. `ctx.pos` instead of just `pos`). Also the context includes set functions (for some reason?), contrary to popular belief, Dragonfly is, in fact, not PocketMine/PHP, and you can just make the properties public by making them uppercase and edit them directly (even then, why would you even use these contexts to begin with).

All in all, this repository doesn't really have much meaning in my book considering it quite literally just takes Dragonfly's handler system... and just makes a new (not so nice) replica of it that sits on top of it and proceeds to call the vanilla system. Please do inform me, again, of what this seeks to fix/improve.

My suggestions to improving this repo are the following:
a. Remove all the handler and context code and just make a common handler that takes in sub-handlers via registry (this still defeats the purpose of the Dragonfly handler system but is a good alternative for those who still want multi-handler support).
b. Delete this repo.

**Comment by aabstractt** [comment]
First learn how make a good code and know when is necessary expose the fields and when not,after it, you can give your opinion, thanks

**Comment by cqdetdev** [comment]
> First learn how make a good code 
i chuckled at irony

> know when is necessary expose the fields and when not,after it
can you please tell me why a) you shouldn't expose a field in a context when you're using that context field to overwrite a pointer anyway and b) the purpose of guarding a field that's already exposed to begin with normally? let me know.

**Comment by aabstractt** [comment]
> > First learn how make a good code
> 
> i chuckled at irony
> 
> > know when is necessary expose the fields and when not,after it
> 
> can you please tell me why a) you shouldn't expose a field in a context when you're using that context field to overwrite a pointer anyway and b) the purpose of guarding a field that's already exposed to begin with normally? let me know.

Only 2 or 3 fields have their Set method, so dont need expose all fields unnecessary and if I expose only the necessary fields it dont looks clean, idk if you know it.

Also I made it for many handlers because if I overwrite each handler because many modules need access to the same handler, it looks bad and isnt clean. If I have 5 handlers at same struct and each handler have +200 line, it looks bad and other developers dont going to know where search… Idk if you know how work with big teams.

**Comment by cqdetdev** [comment]
> Only 2 or 3 fields have their Set method, so dont need expose all fields unnecessary and if I expose only the necessary fields it dont looks clean, idk if you know it.

first of all, set methods typically aren't normal go notation and is just habits from working too much in other OOP languages. secondly, you don't need to keep anything unexposed, there isn't a point in exposing it when they're all fields that were always exposed. 

> Also I made it for many handlers because if I overwrite each handler because many modules need access to the same handler, it looks bad and isnt clean. If I have 5 handlers at same struct and each handler have +200 line, it looks bad and other developers dont going to know where search

a) i already said this is a possible solution but you don't need your extra handlers/contexts to do it and b) you fundamentally don't understand the dragonfly event system if you think this is an issue...

>  Idk if you know how work with big teams.

something i've learned is working in smaller more competent, efficient teams are typically better than larger, incompetent teams. even then, i'll ping @RestartFU who works at a bank and he can provide his input.

**Comment by aabstractt** [comment]
> > Only 2 or 3 fields have their Set method, so dont need expose all fields unnecessary and if I expose only the necessary fields it dont looks clean, idk if you know it.
> 
> first of all, set methods typically aren't normal go notation and is just habits from working too much in other OOP languages. secondly, you don't need to keep anything unexposed, there isn't a point in exposing it when they're all fields that were always exposed.
> 
> > Also I made it for many handlers because if I overwrite each handler because many modules need access to the same handler, it looks bad and isnt clean. If I have 5 handlers at same struct and each handler have +200 line, it looks bad and other developers dont going to know where search
> 
> a) i already said this is a possible solution but you don't need your extra handlers/contexts to do it and b) you fundamentally don't understand the dragonfly event system if you think this is an issue...
> 
> > Idk if you know how work with big teams.
> 
> something i've learned is working in smaller more competent, efficient teams are typically better than larger, incompetent teams. even then, i'll ping @RestartFU who works at a bank and he can provide his input.

- With expose means don't necessary expose setter method, only getter on sometimes... I use my own context because is more fast use a "context" instead of write all variables on each handler function... Speed and clean code :D

- I understand how works the handler system of dragonfly and when I started using dragonfly looks all projects making shit code with many lines at single handler or creating field with other handlers, making main handler calling other handlers but with defined fields... Bad practice (Your public projects have that problems haha)

- I was talking with you, you are giving your opinion but you don't know how work with a big team, so idk why you talk when you are an unexperienced on this stuff...

**Comment by cqdetdev** [comment]
> With expose means don't necessary expose setter method, only getter on sometimes... I use my own context because is more fast use a "context" instead of write all variables on each handler function... Speed and clean code :D

so your definition of speed and clean code is: direct variables from method arguments -> a context -> overwrite original pointers (that were already passed), got it

> I understand how works the handler system of dragonfly and when I started using dragonfly looks all projects making shit code with many lines at single handler or creating field with other handlers, making main handler calling other handlers but with defined fields

this is quite literally what your code does? it's just masked behind a messy implementation and unneeded abstractions so i'm not sure what you're point is here.

> Bad practice (Your public projects have that problems haha)

if your referring to the original vasar dragonfly code a) i did not write that handler code b) that was the first ever implementation of a multi-handler system in dragonfly, it was essentially a prototype that had the flaw and c) the rewrite that was done after that utilized the normal way handlers should be (e.g p.Handler() type checks)

> I was talking with you, you are giving your opinion but you don't know how work with a big team, so idk why you talk when you are an unexperienced on this stuff...

again, chuckling at this irony. i've probably got 3x more experience in dragonfly and even if that weren't the case, at least i am experienced enough to make a server that doesn't run at 10 tps at a 100 players.

**Comment by cqdetdev** [comment]
also, it's not helping your case that 5 other experience dragonfly developers have had a look at this repository and share my views.

**Comment by aabstractt** [comment]
> > With expose means don't necessary expose setter method, only getter on sometimes... I use my own context because is more fast use a "context" instead of write all variables on each handler function... Speed and clean code :D
> 
> so your definition of speed and clean code is: direct variables from method arguments -> a context -> overwrite original pointers (that were already passed), got it
> 
> > I understand how works the handler system of dragonfly and when I started using dragonfly looks all projects making shit code with many lines at single handler or creating field with other handlers, making main handler calling other handlers but with defined fields
> 
> this is quite literally what your code does? it's just masked behind a messy implementation and unneeded abstractions so i'm not sure what you're point is here.
> 
> > Bad practice (Your public projects have that problems haha)
> 
> if your referring to the original vasar dragonfly code a) i did not write that handler code b) that was the first ever implementation of a multi-handler system in dragonfly, it was essentially a prototype that had the flaw and c) the rewrite that was done after that utilized the normal way handlers should be (e.g p.Handler() type checks)
> 
> > I was talking with you, you are giving your opinion but you don't know how work with a big team, so idk why you talk when you are an unexperienced on this stuff...
> 
> again, chuckling at this irony. i've probably got 3x more experience in dragonfly and even if that weren't the case, at least i am experienced enough to make a server that doesn't run at 10 tps at a 100 players.
> 
> I'd look into something called the "Dunning-Kruger Effect" because your responses reek of it.

idk how you can call "experienced" when you never got enough players to do it haha see how I handled 350 single server at 20 tps, something like you never going to see because your shit servers never get players. Stop crying and see how I can do best stuff like you never going to see... Talking with someone without enough experience at teams because his only work was making Minecraft servers with 5 players and calling a "restapi" like "micro service" without knowing his definition... Also hi friends of cadet

**Comment by xKaOz** [comment]
> [!CAUTION]
> cadet is clueless, am I right? @aabstractt

**Comment by aabstractt** [comment]
Also see how looks +200 players at 20 tps, tell me when you see it...
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/59faa98d-c0b7-4ca9-b0c6-a11a7f09fff1" />

**Comment by aabstractt** [comment]
looks more good with 346

https://cdn.discordapp.com/attachments/999062581417357483/1270541945156141138/image.png?ex=67748ee5&is=67733d65&hm=6082e0ca5e414695990708f0be68872afbeb8d6fec066fcd35be0845e35e7295&
![image](https://github.com/user-attachments/assets/50de5007-e2f2-4390-a11f-1e2dbe463069)

**Comment by cqdetdev** [comment]
> idk how you can call "experienced" when you never got enough players to do it haha see how I handled 350 single server at 20 tps, something like you never going to see because your shit servers never get players

well if you think success and experience is based off players your extremely naive. if that were the case, i guess servers like venompvp who had skid developers were very experienced? also i said that it was stress tested at 350 meaning i used moving and chunk loading player simulations...

also anyone can attest to the fact that infinity does not run at 20 tps so boinking your numbers to fit your narrative doesn't help much, curious as to why you have random cpu lod spikes to 100% and cpu usage close to 250%.

> calling a "restapi" like "micro service" without knowing his definition

i will agree it's completely a microservice because it's not stateless but calling it a rest api is comically hillarious

**Comment by cqdetdev** [comment]
https://www.talkspace.com/blog/what-is-the-dunning-kruger-effect-and-how-to-overcome-it/

**Comment by cqdetdev** [comment]
https://www.openmindmag.org/articles/david-dunning-on-expertise

**Comment by cqdetdev** [comment]
https://neurofied.com/the-dunning-kruger-effect/

**Comment by aabstractt** [comment]
> > idk how you can call "experienced" when you never got enough players to do it haha see how I handled 350 single server at 20 tps, something like you never going to see because your shit servers never get players
> 
> well if you think success and experience is based off players your extremely naive. if that were the case, i guess servers like venompvp who had skid developers were very experienced? also i said that it was stress tested at 350 meaning i used moving and chunk loading player simulations...
> 
> also anyone can attest to the fact that infinity does not run at 20 tps so boinking your numbers to fit your narrative doesn't help much, curious as to why you have random cpu lod spikes to 100% and cpu usage close to 250%.
> 
> > calling a "restapi" like "micro service" without knowing his definition
> 
> i will agree it's completely a microservice because it's not stateless but calling it a rest api is comically hillarious

you can't compare "simulation" with real players hahaha I don't say have enough experience for handling many players, my optimization and knowledge is my explanation of why I have experience... Your more known word "skid" but you never show why lmfao its like you are angry because I can show how im more experienced on development than you

**Comment by aabstractt** [comment]
>> also anyone can attest to the fact that infinity does not run at 20 tps so boinking your numbers to fit your narrative doesn't help much, curious as to why you have random cpu lod spikes to 100% and cpu usage close to 250%.

GOOOOD TELL ME YOU ARE IDIOT WITHOUT SAY IT HAHAHAHA you know what is multithreaded? Chunks take big cpu usage, obviously, 350 players loading/unloading chunks async, have high cpu usage... Infinity currently run with 20 tps without lag spike, after removing the sergittos plugins, everything runs very good

**Comment by xKaOz** [comment]
@Sergittos ?!

**Comment by cqdetdev** [comment]
> you can't compare "simulation" with real players 

you can get similar results with, as i literally said, if they are chunk loading and moving and simulating a real player, that is quite literally, the definition of a simulation. if you've worked in anything in web dev, you would know that certain web dev teams use crawlers and such to simulate and see if ui/ux is good, obviously staying eternally in the pocketmine space might not allow you to do such

>  Your more known word "skid" but you never show why lmfao its like you are angry because I can show how im more experienced on development than you

alright i and many other devs would beg to differ lol

> Infinity currently run with 20 tps without lag spike

i guess this explains why pvp is so smooth and knockback is totally not delayed by 5 seconds and players float in the air 👍

**Comment by cqdetdev** [comment]
also, i'm not angry, i literally offered you criticism on how to fix this repository cause i know you are still learning dragonfly (again, by the looks of your own public repos) and you come at me with these antagonizing responses lol

**Comment by aabstractt** [comment]
> > you can't compare "simulation" with real players
> 
> you can get similar results with, as i literally said, if they are chunk loading and moving and simulating a real player, that is quite literally, the definition of a simulation. if you've worked in anything in web dev, you would know that certain web dev teams use crawlers and such to simulate and see if ui/ux is good, obviously staying eternally in the pocketmine space might not allow you to do such

you can't compare web dev with Minecraft server, Minecraft players do more stuff than a web user, because Minecraft players sent a lot of packets, lot of actions, handle many things etc... You don't know about what you talk, but you are here, thinking have experience of what you say

> 
> > Your more known word "skid" but you never show why lmfao its like you are angry because I can show how im more experienced on development than you
> 
> alright i and many other devs would beg to differ lol
Random devs and everyone who say that, are your friends, very wtf no? idk but people who don't know me and you, say different stuff, but people who know me, can say something at my favor and people who are friends from you, can say something at your favor... very xd

> 
> > Infinity currently run with 20 tps without lag spike
> 
> i guess this explains why pvp is so smooth and knockback is totally not delayed by 5 seconds and players float in the air 👍
I see how you are closed to only golang, dragonfly and saying "micro services" to simple restapi and you don't know about other language or software... All issues you said is problem from Nukkit, ye I can fix BUT why? If they don't pay that feature haha the bug isn't my problem without a payment. So you can talk with Alex and say that problems, maybe he listen you haha

**Comment by aabstractt** [comment]
> also, i'm not angry, i literally offered you criticism on how to fix this repository cause i know you are still learning dragonfly (again, by the looks of your own public repos) and you come at me with these antagonizing responses lol

You come like you are the best here... That is criticism... That are you trying "show" how you are "more good" but your comments looks like you don't know how simplify the code of the software that you are trying use.

**Comment by aabstractt** [comment]
> > also, i'm not angry, i literally offered you criticism on how to fix this repository cause i know you are still learning dragonfly (again, by the looks of your own public repos) and you come at me with these antagonizing responses lol
> 
> You come like you are the best here... That is criticism... That are you trying "show" how you are "more good" but your comments looks like you don't know how simplify the code of the software that you are trying use.

You do it every time, looks like if you want attention from everyone, because you only talk shit every time on public about me, but you never go to talk at my md saying nothing, same for restart when I talked with him and after days, he continue talking shit at public but at dm said "cadet is who say everything" mmm you only get attention talking about me or how works everything?

**Comment by cqdetdev** [comment]
> you can't compare web dev with Minecraft server, Minecraft players do more stuff than a web user, because Minecraft players sent a lot of packets, lot of actions, handle many things etc... You don't know about what you talk, but you are here, thinking have experience of what you say

you're missing the point entirely, my point was it's analogous to that and even so, my simulations did a variety of actions (such as movement, swinging, chunking loading, interactions, etc) even then, it's not crazy to believe dragonfly can hold over 300 players without that much latency (also considering we had a multicore i9 to test it)

> Random devs and everyone who say that, are your friends, very wtf no? idk but people who don't know me and you, say different stuff, but people who know me, can say something at my favor and people who are friends from you, can say something at your favor... very xd

ok but that's subjective to you? my "friends" can make their judgments about your abilities and your can to me, but this repository is looked at holistically for what it does and most have deemed it not needed. also i will say that i will take the word of developers from servers/softwares that have more users that infinity since your worth of a developer is based off how many users they get.

> I see how you are closed to only golang, dragonfly and saying "micro services" to simple restapi and you don't know about other language or software... All issues you said is problem from Nukkit, ye I can fix BUT why? If they don't pay that feature haha the bug isn't my problem without a payment. So you can talk with Alex and say that problems, maybe he listen you haha

what? i started with javascript and typescript with discord bots, moved to web dev, then pocketmine, then a mix of webdev, go, and now i do webscraping and data analytics for public health research, you just spewed a bunchof bs lol. and once again, a stateful websocket connection is not a restapi, it's a message broker

> You come like you are the best here... That is criticism... That are you trying "show" how you are "more good" but your comments looks like you don't know how simplify the code of the software that you are trying use.
> You do it every time, looks like if you want attention from everyone, because you only talk shit every time on public about me, but you never go to talk at my md saying nothing, same for restart when I talked with him and after days, he continue talking shit at public but at dm said "cadet is who say everything" mmm you only get attention talking about me or how works everything?

i literally didn't? you can literally go to the top of this issue and see that i asked questions about the relevancy and explained by reasoning, if i was showing how much better i was i would just bash you and i didn't, and if you wanna talk in dms, then by all means message me, the only thing i get out of this atp is chuckling at these responses.

**Comment by aabstractt** [comment]
> ok but that's subjective to you? my "friends" can make their judgments about your abilities and your can to me, but this repository is looked at holistically for what it does and most have deemed it not needed. also i will say that i will take the word of developers from servers/softwares that have more users that infinity since your worth of a developer is based off how many users they get.

I have years of development and experienced, Infinity is the less significant project at my portfolio, clean and optimized core and much more stuff than you can understand. Everyone who can say about this project don't see how you can make more fast features with the context as I made than the currently handlers of dragonfly, writing each variable as parameter of handler function unnecessarily, so more fast using the context as I made, I make getters and setters for the context because many fields don't need to be exposed as setter because it is only a getter, I can expose fields without function when the structure isn't mutable, but on this case, I can't expose the fields, basic concepts of development, why expose all fields when no all need to have their set exposed

**Comment by cqdetdev** [comment]
> much more stuff than you can understand

another case of dunning krugers

>  writing each variable as parameter of handler function unnecessarily

how? ur ide can literally generate this

>  I make getters and setters for the context because many fields don't need to be exposed as setter because it is only a getter, 

the problem is you treat go like its an OOP language and use paradigms from both java and php because it's your only reference point for "clean" code, you can even see an example of this infestation here: https://github.com/aabstractt/quark-api

**Comment by aabstractt** [comment]
I use interfaces because being a PROJECT with many people, we try to avoid giving access to the source code to other developers, so they only have access to the interfaces to be able to work without any problem, you are not going to give source code of the entire project to the entire team and EVEN LESS if several people do not work on that feature, but the feature depends on code from another feature, that is not good project management. At the same time, said project is disgusting and it was source code only because yes, it is not how I have time to work in open source.

**Comment by aabstractt** [comment]
Here you have information how we need to work with big teams to prevent code leaks or sharing unnecessary code, only the needed with his documentation 


<img width="465" alt="image" src="https://github.com/user-attachments/assets/535803a6-08b7-483f-ad6c-d106fc0eb99e" />

**Comment by cqdetdev** [comment]
you can implement that code without all the interfaces and still make it readable, that's my point because it's just infested with the overly abstracted OOP garbage

**Comment by aabstractt** [comment]
not is to make readable, it to prevent give source code lmfao

**Comment by cqdetdev** [comment]
nda's have left the chat

**Comment by aabstractt** [comment]
Yes, well, I've seen how nethergames has obtained leaks of their bedwars and network core, when they have an NDA and being a large team... You won't know who leaks it. You need to work in companies and large teams to be able to understand how we work, and then you can come and criticize...

**Comment by cqdetdev** [comment]
nda's are largely more enforceable in actual firms than a minecraft server... take it from someone who's actually seen source code and the inner workings of an insurance software

**Comment by Booqtecca** [comment]
Culeense los dos y háganse dos hijos, fake devs

**Comment by Booqtecca** [comment]
> @cqdetdev is right

Callate bro por eso te sacan de infinito

**Comment by RestartFU** [comment]
lol this is so funny
